### PR TITLE
Initial kill list

### PR DESCRIPTION
**Pull request by PeterBell**

### CODE REVIEW

**Comment by PeterBell** [comment]
@deadlyvipers - what do you think?

**Comment by PeterBell** [comment]
Hey @githubteacher, what do you think of this?

**Comment by githubteacher** [comment]
I like the idea, but are you sure about the list?

**Comment by PeterBell** [comment]
What do you mean?

**Comment by PeterBell** [comment]
Good point

**Comment by githubteacher** [comment]
That's perfect - let's :ship: this!

**Pull request merged**
